###
GET http://localhost:3001/api/persons/ HTTP/1.1
###
GET http://localhost:3001/api/persons/652e8ecd609a5096270fea66 HTTP/1.1
###
DELETE http://localhost:3001/api/persons/652fca62385ae098fa43bfc0 HTTP/1.1
###
POST http://localhost:3001/api/persons/ HTTP/1.1
Content-Type: application/json

{
    "name": "Jaska Jokunen",
    "number": "040 033 4124"
}
###
PUT http://localhost:3001/api/persons/652fca54882ec97dd8f41e7b HTTP/1.1
Content-Type: application/json

{
    "name": "Janne Jokunen",
    "number": "024 301 4004"
}
###
GET https://phonebook-fso-degenone.onrender.com/api/persons/ HTTP/1.1
###
GET https://phonebook-fso-degenone.onrender.com/api/persons/1 HTTP/1.1
###
DELETE https://phonebook-fso-degenone.onrender.com/api/persons/2 HTTP/1.1
###
POST https://phonebook-fso-degenone.onrender.com/api/persons/ HTTP/1.1
Content-Type: application/json

{
    "name": "Janne Jokunen",
    "number": "020 833 4646"
}
###
PUT https://phonebook-fso-degenone.onrender.com/api/persons/652fca54882ec97dd8f41e7b HTTP/1.1
Content-Type: application/json

{
    "name": "Janne Jokunen",
    "number": "024 301 4004"
}

